# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('bloodgroup', models.CharField(max_length=22)),
                ('birthmark', models.CharField(max_length=44)),
            ],
        ),
    ]
